AUTHN_FAILED = 'urn:oasis:names:tc:SAML:2.0:status:AuthnFailed'
REQUEST_DENIED = 'urn:oasis:names:tc:SAML:2.0:status:RequestDenied'
UNKNOWN_PRINCIPAL = 'urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal'
REQUESTER_GENERAL = 'urn:oasis:names:tc:SAML:2.0:status:Requester'
SUCCESS = 'urn:oasis:names:tc:SAML:2.0:status:Success'
